// LOGIN ACTIONS
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
// USUARIOS ACTIONS
export const GET_ME = "GET_ME";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const CREAR_USUARIO = "CREAR_USUARIO";
export const SELECCIONAR_USUARIO = "SELECCIONAR_USUARIO";
export const ELIMINAR_USUARIO = "ELIMINAR_USUARIO";

// CATEGORIAS ACTIONS
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";

// PRODUCTOS ACTIONS
export const OBTENER_TOTAL_PRODUCTOS = "OBTENER_TOTAL_PRODUCTOS";
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_VENTA = "OBTENER_PRODUCTOS_VENTA";
export const OBTENER_LISTADO_STOCK = "OBTENER_LISTADO_STOCK";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_STOCK = "ELIMINAR_STOCK";
export const OBTENER_REPORTE_PRODUCTOS = "OBTENER_REPORTE_PRODUCTOS";
export const OBTENER_REPORTE_STOCK = "OBTENER_REPORTE_STOCK";
// VENTAS ACTIONS
export const SELECCIONAR_VENTA = "SELECCIONAR_VENTA";
export const SELECCIONAR_VENTA_CANCELADA = "SELECCIONAR_VENTA_CANCELADA";
export const OBTENER_TOTAL_VENTAS = "OBTENER_TOTAL_VENTAS";
export const OBTENER_VENTAS = "OBTENER_VENTAS";
export const OBTENER_LISTADO_VENTAS_HOY = "OBTENER_LISTADO_VENTAS_HOY";
export const OBTENER_VENTAS_HOY = "OBTENER_VENTAS_HOY";
export const OBTENER_VENTAS_ENCABEZADO_HOY = "OBTENER_VENTAS_ENCABEZADO_HOY";
export const OBTENER_VENTAS_GANANCIAS = "OBTENER_VENTAS_GANANCIAS";
export const OBTENER_VENTAS_USUARIOS = "OBTENER_VENTAS_USUARIOS";
export const OBTENER_REPORTE_VENTAS = "OBTENER_REPORTE_VENTAS";
export const OBTENER_REPORTE_VENTAS_CATEGORIA = "OBTENER_REPORTE_VENTAS_CATEGORIA";
export const OBTENER_VENTAS_CANCELADAS = "OBTENER_VENTAS_CANCELADAS";
export const OBTENER_VENTAS_ERROR = "OBTENER_VENTAS_ERROR";
export const AGREGAR_PRODUCTO_CARRITO = "AGREGAR_PRODUCTO_CARRITO";
export const AGREGAR_PRODUCTOS_CARRITO = "AGREGAR_PRODUCTOS_CARRITO";
export const ELIMINAR_PRODUCTO_CARRITO = "ELIMINAR_PRODUCTO_CARRITO";
export const ELIMINAR_REPORTE_VENTAS = "ELIMINAR_REPORTE_VENTAS";
export const AGREGAR_PRODUCTO_CANTIDAD = "AGREGAR_PRODUCTO_CANTIDAD";
export const RESTAR_PRODUCTO_CANTIDAD = "RESTAR_PRODUCTO_CANTIDAD";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const VENTA_REALIZADA = "VENTA_REALIZADA";
export const CAMBIO_TOTAL_VENTA = "CAMBIO_TOTAL_VENTA";
// CAJA ACTIONS
export const OBTENER_CAJAS_GENERAL = "OBTENER_CAJAS_GENERAL";
export const OBTENER_CAJAS_GENERAL_ERROR = "OBTENER_CAJAS_GENERAL_ERROR";
export const ABRIR_CAJA = "ABRIR_CAJA";
export const OBTENER_CAJA = "OBTENER_CAJA";
export const OBTENER_CAJA_ERROR = "OBTENER_CAJA_ERROR";

export const CLEAR_AUTENTICACION = "CLEAR_AUTENTICACION";
export const CLEAR_USUARIOS = "CLEAR_USUARIOS";
export const CLEAR_PRODUCTOS = "CLEAR_PRODUCTOS";
export const CLEAR_CATEGORIAS = "CLEAR_CATEGORIAS";
export const CLEAR_VENTAS = "CLEAR_VENTAS";
export const CLEAR_CAJAS = "CLEAR_CAJAS";
